/* Cria o dominio descrição */
CREATE DOMAIN DESCRICAO VARCHAR(100) NOT NULL;

/* Cria a tabela de usuario */
CREATE TABLE USUARIO(
    ID_USUARIO INTEGER NOT NULL,
    NOME       DESCRICAO,
    SENHA      VARCHAR(30) NOT NULL,
    TIPO       VARCHAR(30) NOT NULL,
    CADASTRO   DATE NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO)
);

/* Cria a tabela  de empresa */
CREATE TABLE EMPRESA(
    ID_EMPRESA   INTEGER NOT NULL,
    RAZA_SOCIAL  DESCRICAO,
    N_FANTAZIA   DESCRICAO,
    ENDERECO     DESCRICAO,
    NUMERO       INTEGER NOT NULL,
    BAIRRO       DESCRICAO,
    CIDADE       DESCRICAO,
    UF           CHAR(2) NOT NULL,
    TELEFONE     VARCHAR(15) NOT NULL,
    CNPJ         VARCHAR(20) NOT NULL,
    EMAIL        DESCRICAO,
    CADASTRO     DATE NOT NULL,
    CONSTRAINT PK_EMPRESA PRIMARY KEY(ID_EMPRESA)
);

/* Cria a tabela de fornecedores */
CREATE TABLE FORNECEDOR(
    ID_FORNECEDOR INTEGER NOT NULL,
    NOME          DESCRICAO,
    ENDERECO      DESCRICAO,
    NUMERO        INTEGER NOT NULL,
    BAIRRO        DESCRICAO,
    CIDADE        DESCRICAO,
    UF            CHAR(2) NOT NULL,
    CEP           VARCHAR(16) NOT NULL,
    TELEFONE      VARCHAR(16) NOT NULL,
    CNPJ          VARCHAR(20) NOT NULL,
    EMAIL         DESCRICAO,
    CADASTRO      DATE NOT NULL,
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY(ID_FORNECEDOR)
);

/* Cria a tabela de clientes */
CREATE TABLE CLIENTE(
    ID_CLIENTE INTEGER NOT NULL,
    NOME       DESCRICAO,
    ENDERECO   DESCRICAO,
    NUMERO     INTEGER NOT NULL,
    BAIRRO     DESCRICAO,
    CIDADE     DESCRICAO,
    UF         CHAR(2) NOT NULL,
    CEP        VARCHAR(16) NOT NULL,
    TELEFONE   VARCHAR(16) NOT NULL,
    CPF        VARCHAR(16) NOT NULL,
    EMAIL      DESCRICAO,
    CADASTRO   DATE NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
);

/* Cria a tabela de produtos */
CREATE TABLE PRODUTO(
    ID_PRODUTO     INTEGER NOT NULL,
    PROD_DESCRICAO DESCRICAO,
    ID_FORNECEDOR  INTEGER NOT NULL,
    VL_CUSTO       DECIMAL(11,2) NOT NULL,
    VL_VENDA       DECIMAL(11,2) NOT NULL,
    ESTOQUE        DECIMAL(11,2) NOT NULL,
    ESTOQUE_MIN    DECIMAL(11,2) NOT NULL,
    UNIDADE        VARCHAR(6),
    CADASTRO       DATE NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO),
    CONSTRAINT FK_FORNECEDOR_PRODUTO FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

SELECT * FROM PRODUTO;






















